import { NavbarLinksInterface } from "@/app/utils/interface/data.interface";

export const NAVBAR_LINKS_DATA: NavbarLinksInterface[] = [
  {
    id: "home",
    label: "Home",
    href: "/",
    type: "link",
    isLink: true,
    target: "_self",
    priority: 1.0,
    dropDown: [],
  },
  {
    id: "about",
    label: "About",
    href: "/about-us",
    type: "link",
    isLink: true,
    target: "_self",
    priority: 0.8,
    dropDown: [],
  },
  {
    id: "services",
    label: "Services",
    href: "/services",
    type: "link",
    isLink: false,
    target: "_self",
    priority: 0.9,
    dropDown: [
      {
        id: "ui-ux-design",
        label: "UI UX Design",
        href: "/services/ui-ux-design",
        type: "link",
        isLink: true,
        target: "_self",
        priority: 0.85,
        dropDown: [],
      },
      {
        id: "saas-development-services",
        label: "SaaS & Web App Development",
        href: "/services/saas-development-services",
        type: "link",
        isLink: true,
        target: "_self",
        priority: 0.85,
        dropDown: [],
      },
      {
        id: "ai-development-automation",
        label: "AI Development & Automation",
        href: "/services/ai-development-services",
        type: "link",
        isLink: true,
        target: "_self",
        priority: 0.85,
        dropDown: [],
      },
      {
        id: "custom-software-development-services",
        label: "Custom Software Development",
        href: "/services/custom-software-development-services",
        type: "link",
        isLink: true,
        target: "_self",
        priority: 0.85,
        dropDown: [],
      },
    ],
  },
  {
    id: "hire",
    label: "Hire",
    href: "/hire",
    type: "link",
    isLink: false,
    target: "_self",
    priority: 0.9,
    dropDown: [
      {
        id: "frontend-engineering",
        label: "Frontend Engineering",
        href: "/hire/frontend",
        type: "link",
        isLink: false,
        target: "_self",
        priority: 0.75,
        dropDown: [
          {
            id: "reactjs-developer",
            label: "React.js Developer",
            href: "/hire/hire-react-js-developers",
            type: "link",
            isLink: true,
            target: "_self",
            priority: 0.8,
            dropDown: [],
          },
          {
            id: "hire-nextjs-developers",
            label: "Next.js Developer",
            href: "/hire/hire-nextjs-developers",
            type: "link",
            isLink: true,
            target: "_self",
            priority: 0.8,
            dropDown: [],
          },
          {
            id: "hire-wordpress-developers",
            label: "WordPress Developer",
            href: "/hire/hire-wordpress-developers",
            type: "link",
            isLink: true,
            target: "_self",
            priority: 0.75,
            dropDown: [],
          },
          {
            id: "hire-gsap-animation-developers",
            label: "GSAP Animation Developer",
            href: "/hire/hire-gsap-animation-developers",
            type: "link",
            isLink: true,
            target: "_self",
            priority: 0.75,
            dropDown: [],
          },
          {
            id: "hire-full-stack-developers",
            label: "Full Stack Developer",
            href: "/hire/hire-full-stack-developers",
            type: "link",
            isLink: true,
            target: "_self",
            priority: 0.8,
            dropDown: [],
          },
          {
            id: "hire-typescript-developers",
            label: "TypeScript Developer",
            href: "/hire/hire-typescript-developers",
            type: "link",
            isLink: true,
            target: "_self",
            priority: 0.75,
            dropDown: [],
          },
          {
            id: "hire-tailwind-css-developers",
            label: "Tailwind CSS Developer",
            href: "/hire/hire-tailwind-css-developers",
            type: "link",
            isLink: true,
            target: "_self",
            priority: 0.75,
            dropDown: [],
          },
        ],
      },
      {
        id: "backend-engineering",
        label: "Backend Engineering",
        href: "/hire/backend",
        type: "link",
        isLink: false,
        target: "_self",
        priority: 0.75,
        dropDown: [
          {
            id: "hire-nodejs-developers",
            label: "Node.js Developer",
            href: "/hire/hire-nodejs-developers",
            type: "link",
            isLink: true,
            target: "_self",
            priority: 0.8,
            dropDown: [],
          },
          {
            id: "hire-fastapi-developers",
            label: "FastAPI Developer",
            href: "/hire/hire-fastapi-developers",
            type: "link",
            isLink: true,
            target: "_self",
            priority: 0.75,
            dropDown: [],
          },
          {
            id: "hire-python-developers",
            label: "Python Developer",
            href: "/hire/hire-python-developers",
            type: "link",
            isLink: true,
            target: "_self",
            priority: 0.75,
            dropDown: [],
          },
        ],
      },
      {
        id: "ui-ux-design",
        label: "UI/UX Design",
        href: "/hire/design",
        type: "link",
        isLink: false,
        target: "_self",
        priority: 0.75,
        dropDown: [
          {
            id: "hire-ui-designers",
            label: "UI Designer",
            href: "/hire/hire-ui-designers",
            type: "link",
            isLink: true,
            target: "_self",
            priority: 0.75,
            dropDown: [],
          },
          {
            id: "hire-wireframe-designers",
            label: "Wireframe Designer",
            href: "/hire/hire-wireframe-designers",
            type: "link",
            isLink: true,
            target: "_self",
            priority: 0.7,
            dropDown: [],
          },
        ],
      },
    ],
  },
  {
    id: "contact",
    label: "Contact",
    href: "/contact",
    type: "link",
    isLink: true,
    target: "_self",
    priority: 0.8,
    dropDown: [],
  },
  {
    id: "blog",
    label: "Blog",
    href: "/blog",
    type: "link",
    isLink: true,
    target: "_self",
    priority: 0.7,
    dropDown: [],
  },
  {
    id: "privacy-policy",
    label: "Privacy Policy",
    href: "/privacy-policy",
    type: "listing",
    isLink: true,
    target: "_self",
    priority: 0.3,
    dropDown: [],
  },
  {
    id: "sitemap",
    label: "Sitemap",
    href: "/sitemap",
    type: "listing",
    isLink: true,
    target: "_self",
    priority: 0.2,
    dropDown: [],
  },
];
