import { OurStepsDataInterface } from "@/app/utils/interface/common.interface";
import { FaCode, FaRegCompass, FaRegLightbulb, FaRocket } from "react-icons/fa";

export const UI_UX_SERVICE_STEPS_WE_FOLLOW: OurStepsDataInterface[] = [
  {
    num: "01",
    title: "Discovery & Insights",
    desc: "We uncover customer needs, business goals, market opportunities, and usability challenges.",
    icon: <FaRegCompass className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-purple-50",
    numBgColor: "bg-purple-100",
    numTextColor: "text-purple-800",
  },
  {
    num: "02",
    title: "UX Strategy & Planning",
    desc: "We create clear information architecture, user journeys, workflows, and interaction frameworks.",
    icon: <FaRegLightbulb className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-yellow-50",
    numBgColor: "bg-yellow-100",
    numTextColor: "text-yellow-800",
  },
  {
    num: "03",
    title: "UI Design & Prototyping",
    desc: "We design polished interfaces and interactive prototypes that bring concepts to life.",
    icon: <FaCode className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-pink-50",
    numBgColor: "bg-pink-100",
    numTextColor: "text-pink-800",
  },
  {
    num: "04",
    title: "Test & Optimize",
    desc: "We continuously refine experiences using feedback, analytics, and user behavior insights.",
    icon: <FaRocket className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-indigo-50",
    numBgColor: "bg-indigo-100",
    numTextColor: "text-indigo-800",
  },
];

export const STEPS_WE_FOLLOW_IN_SERVICES: OurStepsDataInterface[] = [
  {
    num: "01",
    title: "Discovery & Strategy",
    desc: "We understand your business, users and goals to create a clear strategy and roadmap.",
    icon: <FaRegCompass className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-purple-50",
    numBgColor: "bg-purple-100",
    numTextColor: "text-purple-800",
  },
  {
    num: "02",
    title: "Design & Experience",
    desc: "We design intuitive, user-focused experiences that are modern, engaging and conversion-driven.",
    icon: <FaRegLightbulb className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-yellow-50",
    numBgColor: "bg-yellow-100",
    numTextColor: "text-yellow-800",
  },
  {
    num: "03",
    title: "Development & Build",
    desc: "We build scalable, secure and high-performance products using modern technologies.",
    icon: <FaCode className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-pink-50",
    numBgColor: "bg-pink-100",
    numTextColor: "text-pink-800",
  },
  {
    num: "04",
    title: "Launch & Scale",
    desc: "We launch with confidence and continuously optimize to help your product grow and scale.",
    icon: <FaRocket className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-indigo-50",
    numBgColor: "bg-indigo-100",
    numTextColor: "text-indigo-800",
  },
];
export const AI_AUTOMATION_SERVICE_STEPS_WE_FOLLOW: OurStepsDataInterface[] = [
  {
    num: "01",
    title: "Discovery & Strategy",
    desc: "We assess business opportunities, operational challenges, data readiness, and AI use cases to create a practical roadmap aligned with business goals.",
    icon: <FaRegCompass className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-purple-50",
    numBgColor: "bg-purple-100",
    numTextColor: "text-purple-800",
  },
  {
    num: "02",
    title: "Design & Experience",
    desc: "We design intuitive AI experiences that are easy to adopt, user-friendly, and focused on delivering value to both customers and internal teams.",
    icon: <FaRegLightbulb className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-yellow-50",
    numBgColor: "bg-yellow-100",
    numTextColor: "text-yellow-800",
  },
  {
    num: "03",
    title: "Development & Integration",
    desc: "We build secure, scalable, and high-performance AI systems using modern technologies, cloud infrastructure, and industry-leading AI models.",
    icon: <FaCode className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-pink-50",
    numBgColor: "bg-pink-100",
    numTextColor: "text-pink-800",
  },
  {
    num: "04",
    title: "Launch & Optimization",
    desc: "We continuously monitor, refine, and improve AI performance to maximize adoption, efficiency, and return on investment.",
    icon: <FaRocket className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-indigo-50",
    numBgColor: "bg-indigo-100",
    numTextColor: "text-indigo-800",
  },
];
export const CUSTOM_SOFTWARE_SERVICE_STEPS_WE_FOLLOW: OurStepsDataInterface[] = [
  {
    num: "01",
    title: "Discovery & Strategy",
    desc: "We understand your business goals, operational challenges, users, and processes to create a clear software development roadmap.",
    icon: <FaRegCompass className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-purple-50",
    numBgColor: "bg-purple-100",
    numTextColor: "text-purple-800",
  },
  {
    num: "02",
    title: "Design & Experience",
    desc: "We design intuitive user experiences and efficient workflows that improve adoption, productivity, and business outcomes.",
    icon: <FaRegLightbulb className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-yellow-50",
    numBgColor: "bg-yellow-100",
    numTextColor: "text-yellow-800",
  },
  {
    num: "03",
    title: "Development & Engineering",
    desc: "We build scalable, secure, and high-performance software using modern technologies and best development practices.",
    icon: <FaCode className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-pink-50",
    numBgColor: "bg-pink-100",
    numTextColor: "text-pink-800",
  },
  {
    num: "04",
    title: "Launch & Growth",
    desc: "We deploy with confidence and continuously improve performance, scalability, and functionality as your business evolves.",
    icon: <FaRocket className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-indigo-50",
    numBgColor: "bg-indigo-100",
    numTextColor: "text-indigo-800",
  },
];
export const SAAS_DEVELOPMENT_SERVICE_STEPS_WE_FOLLOW: OurStepsDataInterface[] = [
  {
    num: "01",
    title: "Discovery & Strategy",
    desc: "We align business goals, user needs, market opportunities, and technical requirements into a clear execution plan.",
    icon: <FaRegCompass className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-purple-50",
    numBgColor: "bg-purple-100",
    numTextColor: "text-purple-800",
  },
  {
    num: "02",
    title: "Design & Experience",
    desc: "We create intuitive, conversion-focused user experiences that improve adoption, engagement, and retention.",
    icon: <FaRegLightbulb className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-yellow-50",
    numBgColor: "bg-yellow-100",
    numTextColor: "text-yellow-800",
  },
  {
    num: "03",
    title: "Development & Engineering",
    desc: "Our engineers build scalable software architectures that support performance, security, and future expansion.",
    icon: <FaCode className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-pink-50",
    numBgColor: "bg-pink-100",
    numTextColor: "text-pink-800",
  },
  {
    num: "04",
    title: "Launch & Growth",
    desc: "We help launch confidently while continuously optimizing for user feedback, business performance, and growth opportunities.",
    icon: <FaRocket className="w-4 h-4 md:w-6 md:h-6 text-gray-800" />,
    iconBgColor: "bg-indigo-50",
    numBgColor: "bg-indigo-100",
    numTextColor: "text-indigo-800",
  },
];
