import NavBarComponent from "@/app/components/navbar/navBar";
import "@/app/styles/globals.css";
import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import SmoothScrollProvider from "./components/smoothScrollProvider";
import { RootLayoutInterface } from "./utils/interface/common.interface";

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutInterface) {
  return (
    <html lang="en" className={`${playfairDisplay.variable} ${inter.variable} h-full antialiased`}>
      <body className="w-full h-full">
        <SmoothScrollProvider>
          <NavBarComponent />
          {children}
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
