import NavBarComponent from "@/app/components/navbar/navBar";
import "@/app/styles/globals.css";
import type { Metadata } from "next";
import { Instrument_Sans, Inter, Playfair_Display } from "next/font/google";
import SmoothScrollProvider from "./components/smoothScrollProvider";
import { RootLayoutInterface } from "./utils/interface/common.interface";
import FooterScreen from "@/app/screens/common/footerScreen";

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutInterface) {
  return (
    <html lang="en" className={`${playfairDisplay.variable} ${inter.variable} ${instrumentSans.variable} antialiased`}>
      <body className="w-full">
        <SmoothScrollProvider>
          <NavBarComponent />
          {children}
          <div className="w-full overflow-hidden">
            <FooterScreen />
          </div>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
